<?php

/**
 * @file
 * Primary module hooks for My Module module.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;


/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function my_module_node_presave(NodeInterface $entity) {
    if ($entity->bundle() === 'contact') {
        $entity->setTitle($entity->get('field_first_name')->getString() . ' ' . $entity->get('field_last_name')->getString());
    }
}

/**
 * Implements hook_ENTITY_TYPE_create().
 */
function my_module_node_create(\Drupal\Core\Entity\EntityInterface $entity) {
    if ($entity->bundle() === 'contact') {
        $entity->setTitle('*placeholder*');
    }
}

/**
 * Implements hook_entity_field_access().
 */
function my_module_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {
    if ($operation === 'edit' && $field_definition->getTargetEntityTypeId() === 'node' && $field_definition->getTargetBundle() === 'contact') {
        $field_name = $field_definition->getName();
        if ($field_name === 'title') {
           return AccessResult::forbidden();
        }
    }
  return AccessResult::neutral();
}
